project_id = "zvwybyootzmrrvyxctgm"

[functions.extract-recipe]
verify_jwt = false

[functions.extract-recipe-from-images]
verify_jwt = false

[functions.meal-plan-chat]
verify_jwt = false

[functions.translate-recipes]
verify_jwt = false
